platform :ios, '26.0'
inhibit_all_warnings!

target 'Example-Point' do
  use_frameworks!

  pod 'KeychainAccess', '~> 4.2'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'TextFieldEffects', '~> 1.6'
  pod 'PMAlertController', '~> 4.0'
  pod 'Toast-Swift', '~> 5.1'
  pod 'IrohaSwift', :path => '../../i23/IrohaSwift'
  pod 'NoritoBridge', :path => '../Vendor/NoritoBridge'

  target 'Example-PointTests' do
    inherit! :search_paths
  end

  target 'Example-PointUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '6.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '26.0'
    end
  end
end
